#!/usr/bin/ruby

require 'db'
require 'rubygems'
require 'ruby-prof'

bad_pages = [
  'List of Danish football transfers summer 2008',
  'Baku',
  'List of Brigham Young University alumni',
  '1998 FIFA World Cup qualification (UEFA)',
  'Statewide opinion polling for the Republican Party presidential primaries, 2012',
  'Opinion polling for the United States House of Representatives elections, 2010',
  ]

bad_pages.each do |article|
  page,date = retrieve_article article

  t = Time.now
  result = RubyProf.profile do
    scrape_article page
  end
  $stderr.puts "Parsing #{article} took #{Time.now-t} seconds"

  File.open "profile.#{ article.gsub(/\s/, '_') }.out", 'w' do |fout|
    printer = RubyProf::GraphPrinter.new result
    printer.print fout
  end
end


